/**
 * English & French search aliases for CommandPalette.
 * Arabic labels/descriptions in navigation.ts remain the primary display text.
 */
export const navSearchKeywords: Record<string, string[]> = {
  "/": [
    "home",
    "accueil",
    "main",
    "page principale",
  ],
  "/inscription": [
    "registration",
    "enrollment",
    "enrolment",
    "inscription",
    "university registration",
    "admission",
    "enregistrement",
  ],
  "/inscription/foyer": [
    "dorm registration",
    "housing registration",
    "foyer registration",
    "inscription foyer",
    "inscription residence",
    "residence universitaire",
  ],
  "/library": [
    "library",
    "bibliotheque",
    "bibliothèque",
    "books",
    "exams",
    "examens",
    "livres",
    "references",
  ],
  "/departments": [
    "departments",
    "departements",
    "départements",
    "sections",
    "specialties",
    "specialites",
    "spécialités",
    "TI",
    "SEG",
    "GPR",
  ],
  "/masters": [
    "master",
    "masters",
    "maitrise",
    "maîtrise",
    "graduate",
    "postgraduate",
  ],
  "/housing": [
    "housing",
    "dormitory",
    "dorm",
    "hostel",
    "residence",
    "résidence",
    "foyer",
    "foyers",
    "logement",
    "hebergement",
    "hébergement",
  ],
  "/bourse": [
    "scholarship",
    "scholarships",
    "bourse",
    "grant",
    "financial aid",
    "aide financiere",
    "aide financière",
    "minhah",
  ],
  "/transport": [
    "transport",
    "transportation",
    "bus",
    "buses",
    "louage",
    "louages",
    "commute",
    "transports",
    "mobilite",
    "mobilité",
  ],
  "/resto": [
    "restaurant",
    "cafeteria",
    "canteen",
    "resto",
    "cantine",
    "meals",
    "repas",
    "menu",
  ],
  "/clubs": [
    "clubs",
    "club",
    "associations",
    "activities",
    "activites",
    "activités",
    "student clubs",
  ],
  "/stages": [
    "internship",
    "internships",
    "stage",
    "stages",
    "traineeship",
    "training",
    "tarbous",
    "tadrib",
  ],
  "/stages/companies": [
    "companies",
    "company",
    "entreprises",
    "societes",
    "sociétés",
    "employers",
    "annuaire",
    "directory",
    "repertoire",
    "répertoire",
  ],
  "/stages/pfe": [
    "PFE",
    "final year project",
    "graduation project",
    "projet fin etudes",
    "projet fin d'etudes",
    "projet de fin d'etudes",
    "projet de fin d'études",
    "end of studies project",
  ],
  "/explore": [
    "explore",
    "discover",
    "zaghouan",
    "city",
    "ville",
    "tourism",
    "tourisme",
    "places",
    "lieux",
  ],
  "/faq": [
    "FAQ",
    "questions",
    "help",
    "aide",
    "answers",
    "reponses",
    "réponses",
    "frequently asked",
  ],
  "/bonus": [
    "tips",
    "advice",
    "bonus",
    "credits",
    "thanks",
    "acknowledgements",
    "conseils",
    "remerciements",
  ],
  "/clubs/securinets": [
    "SecuriNets",
    "cybersecurity",
    "cyber security",
    "security",
    "securite",
    "sécurité",
    "informatique securisee",
  ],
  "/clubs/robotique": [
    "robotics",
    "robotique",
    "robots",
    "electronics",
    "electronique",
    "électronique",
    "programming",
    "programmation",
  ],
  "/clubs/enactus": [
    "Enactus",
    "entrepreneurship",
    "entrepreneuriat",
    "business",
    "projects",
    "projets",
  ],
  "/clubs/ieee": [
    "IEEE",
    "TSYP",
    "engineering",
    "ingenierie",
    "ingénierie",
    "workshops",
    "ateliers",
  ],
  "/clubs/sos-ambassadeurs": [
    "SOS",
    "ambassadors",
    "ambassadeurs",
    "volunteer",
    "volunteering",
    "benevolat",
    "bénévolat",
    "charity",
  ],
  "/departments/ti": [
    "TI",
    "IT",
    "information technology",
    "informatique",
    "DSI",
    "RSI",
    "software",
    "logiciel",
    "reseaux",
    "réseaux",
  ],
  "/departments/seg": [
    "SEG",
    "economics",
    "economie",
    "économie",
    "management",
    "gestion",
    "accounting",
    "comptabilite",
    "comptabilité",
    "finance",
  ],
  "/departments/gpr": [
    "GPR",
    "chemical engineering",
    "genie des procedes",
    "génie des procédés",
    "process engineering",
    "chimie",
    "chemistry",
  ],
};

export const categorySearchKeywords: Record<string, string[]> = {
  academic: ["academic", "academics", "academique", "académique", "studies", "etudes", "études"],
  life: ["life", "student life", "vie", "vie etudiante", "vie étudiante", "daily"],
  career: ["career", "carriere", "carrière", "internship", "stage", "emploi", "job"],
  campus: ["campus", "city", "ville", "other", "autre"],
};
